const storage=require('../../utils/storage');const dates=require('../../utils/date');const theme=require('../../utils/theme');const media=require('../../utils/media');
Page({
  data:{themeClass:'',targets:{},theme:'light'},
  onShow(){const state=storage.getDietState();this.setData({themeClass:theme.apply(),targets:state.settings.targets,theme:state.settings.theme});},
  inputTarget(event){this.setData({[`targets.${event.currentTarget.dataset.field}`]:event.detail.value});},
  preset(event){const calories=Math.max(1,Number(this.data.targets.calories)||1600);const mode=event.currentTarget.dataset.mode;const ratios=mode==='fatloss'?[.4,.35,.25]:[.5,.25,.25];this.setData({'targets.carbs':Math.round(calories*ratios[0]/4),'targets.protein':Math.round(calories*ratios[1]/4),'targets.fat':Math.round(calories*ratios[2]/9)});},
  save(){const state=storage.getDietState();state.settings.targets={calories:Math.max(1,Number(this.data.targets.calories)||1600),carbs:Math.max(0,Number(this.data.targets.carbs)||0),protein:Math.max(0,Number(this.data.targets.protein)||0),fat:Math.max(0,Number(this.data.targets.fat)||0)};state.settings.theme=this.data.theme;storage.saveDietState(state);this.setData({themeClass:theme.apply()});wx.showToast({title:'设置已保存',icon:'success'});},
  changeTheme(event){this.setData({theme:event.detail.value?'dark':'light'},()=>this.save());},
  async exportBackup(){wx.showLoading({title:'正在生成备份'});try{const backup=await media.embedBackupImages(storage.createBackup());const data=JSON.stringify(backup,null,2);const path=`${wx.env.USER_DATA_PATH}/营养训练备份-${dates.dateKey(Date.now())}.json`;await new Promise((resolve,reject)=>wx.getFileSystemManager().writeFile({filePath:path,data,encoding:'utf8',success:resolve,fail:reject}));wx.hideLoading();if(wx.shareFileMessage)wx.shareFileMessage({filePath:path,fileName:path.split('/').pop(),fail:()=>wx.showModal({title:'备份已生成',content:'文件已保存在小程序本地文件中。',showCancel:false})});else wx.showModal({title:'备份已生成',content:'当前微信版本不支持直接分享文件，请升级微信后重试。',showCancel:false});}catch(error){wx.hideLoading();wx.showToast({title:'导出失败',icon:'none'});}},
  importBackup(){wx.chooseMessageFile({count:1,type:'file',extension:['json'],success:result=>{const path=result.tempFiles[0].path;wx.getFileSystemManager().readFile({filePath:path,encoding:'utf8',success:file=>{try{const parsed=JSON.parse(file.data);wx.showModal({title:'导入本地备份',content:'导入会合并饮食、训练和自定义数据，不会删除当前记录。',success:async answer=>{if(!answer.confirm)return;wx.showLoading({title:'正在导入'});try{const payload=await media.restoreBackupImages(parsed);storage.importBackup(payload);wx.hideLoading();this.onShow();wx.showToast({title:'导入成功',icon:'success'});}catch(error){wx.hideLoading();wx.showModal({title:'导入失败',content:error.message||'文件格式不正确',showCancel:false});}}});}catch(error){wx.showModal({title:'导入失败',content:error.message||'文件格式不正确',showCancel:false});}},fail:()=>wx.showToast({title:'读取文件失败',icon:'none'})});}});},
  clearAll(){wx.showModal({title:'清除全部本地数据',content:'将删除饮食、训练、自定义食物、照片和设置，且无法撤销。建议先导出备份。',confirmText:'全部删除',confirmColor:'#d64545',success:result=>{if(!result.confirm)return;media.clearAllImages();storage.clearUserData();this.onShow();wx.showToast({title:'已清除',icon:'success'});}});},
});
